### ISSUE TITLE
Nicht mit header kompatibel

### ISSUE THREAD

**Issue by gckoeppel** [HSR-Stud/idiotenseite#5]
Die Idiotenseite lässt sich mit dem aktuellen Standardheader https://github.com/HSR-Stud/header nicht builden. Bei DigSig1 musste ich folgendes hinzufügen:

\usepackage{circuitikz}
\usepackage{multicol}
\usepackage{rotating}
\newcommand{\formelbuch}[1]{$_{\textcolor{red}{\mbox{\small{S#1}}}}$}
\newcommand{\arraystretchOriginal}{1}

Achtung! Diese Liste ist womöglich nicht komplett da bereits einige andere Packages hinzugefügt waren.

**Comment by wrd90** [comment]
Obwohl dieses issue sehr alt ist: mittlerweile wurde der header2.0 branch in den master gemerged weil der "alte" master ja nicht mehr verwendet werden soll für neue Zusammenfassungen. Und soeben habe ich circuitikz in den header hinzugefügt, damit ist der letzte Stand des headers mit dem letzten Stand der Idiotenseite kompatibel. Somit halte ich dieses issue für gefixt.

**Comment by wrd90** [comment]
Fixed by ba9bb4deafae0987d84d010c7b62a093295402ac
